// Generated by gencpp from file meno_matky_za_slobodna/DrawRequest.msg
// DO NOT EDIT!


#ifndef MENO_MATKY_ZA_SLOBODNA_MESSAGE_DRAWREQUEST_H
#define MENO_MATKY_ZA_SLOBODNA_MESSAGE_DRAWREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace meno_matky_za_slobodna
{
template <class ContainerAllocator>
struct DrawRequest_
{
  typedef DrawRequest_<ContainerAllocator> Type;

  DrawRequest_()
    : speed(0)
    , angle(0)  {
    }
  DrawRequest_(const ContainerAllocator& _alloc)
    : speed(0)
    , angle(0)  {
  (void)_alloc;
    }



   typedef int64_t _speed_type;
  _speed_type speed;

   typedef int64_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DrawRequest_

typedef ::meno_matky_za_slobodna::DrawRequest_<std::allocator<void> > DrawRequest;

typedef boost::shared_ptr< ::meno_matky_za_slobodna::DrawRequest > DrawRequestPtr;
typedef boost::shared_ptr< ::meno_matky_za_slobodna::DrawRequest const> DrawRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator1> & lhs, const ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator1> & lhs, const ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace meno_matky_za_slobodna

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7dbf0c6999eb0581666a605aa6b1d8e6";
  }

  static const char* value(const ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7dbf0c6999eb0581ULL;
  static const uint64_t static_value2 = 0x666a605aa6b1d8e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "meno_matky_za_slobodna/DrawRequest";
  }

  static const char* value(const ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 speed\n"
"int64 angle\n"
;
  }

  static const char* value(const ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrawRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::meno_matky_za_slobodna::DrawRequest_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int64_t>::stream(s, indent + "  ", v.speed);
    s << indent << "angle: ";
    Printer<int64_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MENO_MATKY_ZA_SLOBODNA_MESSAGE_DRAWREQUEST_H
