// Generated by gencpp from file meno_matky_za_slobodna/Start.msg
// DO NOT EDIT!


#ifndef MENO_MATKY_ZA_SLOBODNA_MESSAGE_START_H
#define MENO_MATKY_ZA_SLOBODNA_MESSAGE_START_H

#include <ros/service_traits.h>


#include <meno_matky_za_slobodna/StartRequest.h>
#include <meno_matky_za_slobodna/StartResponse.h>


namespace meno_matky_za_slobodna
{

struct Start
{

typedef StartRequest Request;
typedef StartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Start
} // namespace meno_matky_za_slobodna


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::meno_matky_za_slobodna::Start > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::meno_matky_za_slobodna::Start&) { return value(); }
};

template<>
struct DataType< ::meno_matky_za_slobodna::Start > {
  static const char* value()
  {
    return "meno_matky_za_slobodna/Start";
  }

  static const char* value(const ::meno_matky_za_slobodna::Start&) { return value(); }
};


// service_traits::MD5Sum< ::meno_matky_za_slobodna::StartRequest> should match
// service_traits::MD5Sum< ::meno_matky_za_slobodna::Start >
template<>
struct MD5Sum< ::meno_matky_za_slobodna::StartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::meno_matky_za_slobodna::Start >::value();
  }
  static const char* value(const ::meno_matky_za_slobodna::StartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::meno_matky_za_slobodna::StartRequest> should match
// service_traits::DataType< ::meno_matky_za_slobodna::Start >
template<>
struct DataType< ::meno_matky_za_slobodna::StartRequest>
{
  static const char* value()
  {
    return DataType< ::meno_matky_za_slobodna::Start >::value();
  }
  static const char* value(const ::meno_matky_za_slobodna::StartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::meno_matky_za_slobodna::StartResponse> should match
// service_traits::MD5Sum< ::meno_matky_za_slobodna::Start >
template<>
struct MD5Sum< ::meno_matky_za_slobodna::StartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::meno_matky_za_slobodna::Start >::value();
  }
  static const char* value(const ::meno_matky_za_slobodna::StartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::meno_matky_za_slobodna::StartResponse> should match
// service_traits::DataType< ::meno_matky_za_slobodna::Start >
template<>
struct DataType< ::meno_matky_za_slobodna::StartResponse>
{
  static const char* value()
  {
    return DataType< ::meno_matky_za_slobodna::Start >::value();
  }
  static const char* value(const ::meno_matky_za_slobodna::StartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MENO_MATKY_ZA_SLOBODNA_MESSAGE_START_H
