// Generated by gencpp from file meno_matky_za_slobodna/StopRequest.msg
// DO NOT EDIT!


#ifndef MENO_MATKY_ZA_SLOBODNA_MESSAGE_STOPREQUEST_H
#define MENO_MATKY_ZA_SLOBODNA_MESSAGE_STOPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace meno_matky_za_slobodna
{
template <class ContainerAllocator>
struct StopRequest_
{
  typedef StopRequest_<ContainerAllocator> Type;

  StopRequest_()
    : stop(false)  {
    }
  StopRequest_(const ContainerAllocator& _alloc)
    : stop(false)  {
  (void)_alloc;
    }



   typedef uint8_t _stop_type;
  _stop_type stop;





  typedef boost::shared_ptr< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopRequest_

typedef ::meno_matky_za_slobodna::StopRequest_<std::allocator<void> > StopRequest;

typedef boost::shared_ptr< ::meno_matky_za_slobodna::StopRequest > StopRequestPtr;
typedef boost::shared_ptr< ::meno_matky_za_slobodna::StopRequest const> StopRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator1> & lhs, const ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator2> & rhs)
{
  return lhs.stop == rhs.stop;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator1> & lhs, const ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace meno_matky_za_slobodna

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71f1172402e56b82716ca71681cded6b";
  }

  static const char* value(const ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71f1172402e56b82ULL;
  static const uint64_t static_value2 = 0x716ca71681cded6bULL;
};

template<class ContainerAllocator>
struct DataType< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "meno_matky_za_slobodna/StopRequest";
  }

  static const char* value(const ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool stop\n"
;
  }

  static const char* value(const ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::meno_matky_za_slobodna::StopRequest_<ContainerAllocator>& v)
  {
    s << indent << "stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MENO_MATKY_ZA_SLOBODNA_MESSAGE_STOPREQUEST_H
