// Generated by gencpp from file meno_matky_za_slobodna/Stop.msg
// DO NOT EDIT!


#ifndef MENO_MATKY_ZA_SLOBODNA_MESSAGE_STOP_H
#define MENO_MATKY_ZA_SLOBODNA_MESSAGE_STOP_H

#include <ros/service_traits.h>


#include <meno_matky_za_slobodna/StopRequest.h>
#include <meno_matky_za_slobodna/StopResponse.h>


namespace meno_matky_za_slobodna
{

struct Stop
{

typedef StopRequest Request;
typedef StopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Stop
} // namespace meno_matky_za_slobodna


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::meno_matky_za_slobodna::Stop > {
  static const char* value()
  {
    return "5fb7f99d98a30bfd9eeddbb34b138b31";
  }

  static const char* value(const ::meno_matky_za_slobodna::Stop&) { return value(); }
};

template<>
struct DataType< ::meno_matky_za_slobodna::Stop > {
  static const char* value()
  {
    return "meno_matky_za_slobodna/Stop";
  }

  static const char* value(const ::meno_matky_za_slobodna::Stop&) { return value(); }
};


// service_traits::MD5Sum< ::meno_matky_za_slobodna::StopRequest> should match
// service_traits::MD5Sum< ::meno_matky_za_slobodna::Stop >
template<>
struct MD5Sum< ::meno_matky_za_slobodna::StopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::meno_matky_za_slobodna::Stop >::value();
  }
  static const char* value(const ::meno_matky_za_slobodna::StopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::meno_matky_za_slobodna::StopRequest> should match
// service_traits::DataType< ::meno_matky_za_slobodna::Stop >
template<>
struct DataType< ::meno_matky_za_slobodna::StopRequest>
{
  static const char* value()
  {
    return DataType< ::meno_matky_za_slobodna::Stop >::value();
  }
  static const char* value(const ::meno_matky_za_slobodna::StopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::meno_matky_za_slobodna::StopResponse> should match
// service_traits::MD5Sum< ::meno_matky_za_slobodna::Stop >
template<>
struct MD5Sum< ::meno_matky_za_slobodna::StopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::meno_matky_za_slobodna::Stop >::value();
  }
  static const char* value(const ::meno_matky_za_slobodna::StopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::meno_matky_za_slobodna::StopResponse> should match
// service_traits::DataType< ::meno_matky_za_slobodna::Stop >
template<>
struct DataType< ::meno_matky_za_slobodna::StopResponse>
{
  static const char* value()
  {
    return DataType< ::meno_matky_za_slobodna::Stop >::value();
  }
  static const char* value(const ::meno_matky_za_slobodna::StopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MENO_MATKY_ZA_SLOBODNA_MESSAGE_STOP_H
